# Tensorflow VS PyTorch
In this notebook we will see some basic exercise with torch and tensorflow.

We will see 3 basic exercise.




## import necessary libraries
First of all we need to import the necesarry libraries.

In [1]:
import torch

In [2]:
import tensorflow as tf

## Exercise 1
**Initialisation and Tensor Operations**

**Goal**: Create a 2D tensor of size 3×3 containing random numbers, perform sum, product and transpose operations on it.
### PyTorch
- Initialise a tensor of size 3×3 with random numbers → `torch.rand(3, 3)`
- Calculates the sum of all elements of the tensor → `tensor.sum()`
- Calculate the product between the original tensor and its transpose → `tensor.T and torch.mm(tensor, tensor_transposed)`
- Checks that the result is symmetric → `torch.allclose(product_tensor, product_tensor.T)`

### Tensorflow

-	Initialise a tensor of size 3×3 with random numbers
→ `tf.random.uniform((3, 3), minval=0, maxval=1)`
- Calculate the sum of all elements of the tensor
→ `tf.reduce_sum(tensor)`
- Compute the product between the original tensor and its transpose
→ `tf.transpose(tensor) and tf.matmul(tensor, tensor_transposed)`
- Check that the result is symmetric
→ `tf.reduce_all(tf.abs(product_tensor - tf.transpose(product_tensor)) < 1e-6)`



In [3]:
#### PYTORCH

#  Create a 2D tensor of size 3×3 containing random numbers
tensor = torch.rand(3,3)
print("Initial Tensor:\n", tensor)

# Calculates the sum of all elements of the tensor
sum_tensor = tensor.sum()
print("Sum of all elements:\n", sum_tensor)

# Calculate the product between the original tensor and its transpose
tensor_transposed = tensor.T
product_tensor = torch.mm(tensor, tensor_transposed)
print("Product between the original tensor and its transpose:\n", product_tensor)

# Checks that the result is symmetric
is_symmetric = torch.allclose(product_tensor, product_tensor.T)
print("The result is symmetric:", is_symmetric)

Initial Tensor:
 tensor([[0.2231, 0.1905, 0.9229],
        [0.3097, 0.9580, 0.1001],
        [0.4894, 0.1690, 0.2521]])
Sum of all elements:
 tensor(3.6147)
Product between the original tensor and its transpose:
 tensor([[0.9378, 0.3439, 0.3740],
        [0.3439, 1.0236, 0.3387],
        [0.3740, 0.3387, 0.3316]])
The result is symmetric: True


In [4]:
#### TENSORFLOW

#  Create a 2D tensor of size 3×3 containing random numbers
tensor = tf.random.uniform((3, 3), minval=0, maxval=1)
print("Initial Tensor:\n", tensor)

# Calculates the sum of all elements of the tensor
sum_tensor = tf.reduce_sum(tensor)
print("Sum of all elements:\n", sum_tensor)

# Calculate the product between the original tensor and its transpose
tensor_transposed = tf.transpose(tensor)
product_tensor = tf.matmul(tensor, tensor_transposed)
print("Product between the original tensor and its transpose:\n", product_tensor)

# Checks that the result is symmetric
is_symmetric = tf.reduce_all(tf.abs(product_tensor - tf.transpose(product_tensor)) < 1e-6)
print("The result is symmetric:", is_symmetric)

Initial Tensor:
 tf.Tensor(
[[0.76907766 0.03052926 0.64520895]
 [0.13454461 0.7728865  0.17866457]
 [0.10483193 0.4702592  0.10228169]], shape=(3, 3), dtype=float32)
Sum of all elements:
 tf.Tensor(3.2082844, shape=(), dtype=float32)
Product between the original tensor and its transpose:
 tf.Tensor(
[[1.008707   0.2423469  0.16097362]
 [0.2423469  0.64737684 0.3958357 ]
 [0.16097362 0.3958357  0.24259499]], shape=(3, 3), dtype=float32)
The result is symmetric: tf.Tensor(True, shape=(), dtype=bool)


## Exercise 2

**Autograd and Gradient Calculation**

**Goal**: Define a simple function and compute gradients with respect to scalar variables.

1. Define two variables `x` and `y` as scalar tensors with `requires_grad=True`.
2. Define the function:  
   
   f(x, y) = 3x^2 + 2y^2 + xy

3. Compute the gradient of \( f \) with respect to \( x \) and \( y \).

### Torch
1. `torch.tensor(2.0, requires_grad=True)`
2. `3 * x**2 + 2 * y**2 + x * y`
3. `f.backward()`

### Tensorflow
1. `tf.Variable(2.0)`
2. `3 * x**2 + 2 * y**2 + x * y`
3. `tape.gradient(f, [x, y])`


In [5]:
### PYTORCH

# Define scalar variables with requires_grad=True
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Define the function
f = 3 * x**2 + 2 * y**2 + x * y

# Compute gradients
f.backward()

# Print gradients
print("Gradient with respect to x:", x.grad)
print("Gradient with respect to y:", y.grad)

Gradient with respect to x: tensor(15.)
Gradient with respect to y: tensor(14.)


In [6]:
### Tensorflow

# Define scalar variables
x = tf.Variable(2.0)
y = tf.Variable(3.0)

# Use GradientTape to track computations
with tf.GradientTape() as tape:
    f = 3 * x**2 + 2 * y**2 + x * y

# Compute gradients
gradients = tape.gradient(f, [x, y])

# Print gradients
print("Gradient with respect to x:", gradients[0].numpy())
print("Gradient with respect to y:", gradients[1].numpy())

Gradient with respect to x: 15.0
Gradient with respect to y: 14.0


## **Exercise 3**

**Convolutional Neural Network (CNN) Implementation**

**Goal**: Implement a simple **Convolutional Neural Network (CNN)** and train it on a benchmark dataset such as **MNIST** or **CIFAR-10**.

1. Create a **CNN** with:
   - Two convolutional layers
   - One fully connected layer
2. Train the model on a dataset like **MNIST** or **CIFAR-10**.
3. Evaluate the model's performance.

### **Define the CNN Model**
#### **Torch**
*usefull function:*


```python
    nn.Conv2d(INPUT_CHANNEL, N_OUTPUT, kernel_size=3, padding=1)
    nn.Linear(N_INPUT, N_OUTPUT)
    torch.relu(INPUT_LAYER)
    torch.max_pool2d(INPUT_LAYER, POOL_SIZE)
    x.view(x.size(0), -1)  # Flatten
```
**note:**
if I have 2 conv2d is maxpooling (2x2) with 32 and 63 channels respectively and input dimensions 28 × 28 (like MNIST) after conv I have 64 × 7 × 7 dimensions derived from the convolution and pooling operations that reduce the original input (1, 28, 28) into a feature map (64, 7, 7) before being flattened for the fully connected layer.

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

# Define CNN model
class CNN(nn.Module):
       def __init__(self):
           super(CNN, self).__init__()
           self.conv1 = nn.Conv2d(1, 32, kernel_size=3, padding=1)
           self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
           self.fc1 = nn.Linear(64 * 7 * 7, 10)

       def forward(self, x):
           x = torch.relu(self.conv1(x))
           x = torch.max_pool2d(x, 2)
           x = torch.relu(self.conv2(x))
           x = torch.max_pool2d(x, 2)
           x = x.view(x.size(0), -1)  # Flatten
           x = self.fc1(x)
           return x

#### **TF**
*usefull function:*


```python
    tf.keras.layers.Conv2D(N_OUTPUT, (K_size, K_SIZE), activation='relu', padding='same', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((POOL_SIZE, POOL_SIZE)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(N_OUTPUT, activation='softmax')
```
**note:** In tensorflow, the input dimension is automatically calculated from the previous layer.


In [8]:
# Define CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=(28, 28, 1)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(10, activation='softmax')
])

/Users/alicebizzarri/Desktop/PhD/Presentazioni/Corsi/ml_env/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### **Load and preprocess Data**
#### **Torch**

*Usefull function:*



```python
transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
```



In [9]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
train_dataset = torchvision.datasets.MNIST(root='./data', train=True, transform=transform, download=True)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)

100.0%
100.0%
100.0%
100.0%


#### **TF**
*usefull function:*


```python
    (x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
```



In [10]:
(x_train, y_train), _ = tf.keras.datasets.mnist.load_data()
x_train = x_train / 255.0  # Normalize

### **Train the Model**
#### **Torch**

*Usefull function:*



```python
nn.CrossEntropyLoss()
optim.Adam(model.parameters(), lr=0.001)

optimizer.zero_grad()
model(images)
loss.backward()
optimizer.step()

```



In [11]:
model = CNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 10

for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
print("Training complete.")

Epoch 1/10
Epoch 2/10
Epoch 3/10
Epoch 4/10
Epoch 5/10
Epoch 6/10
Epoch 7/10
Epoch 8/10
Epoch 9/10
Epoch 10/10
Training complete.


#### **TF**
*usefull function:*


```python
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
    model.fit(x_train, y_train, epochs=100, batch_size=64)
```


In [12]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5, batch_size=64)
print("Training complete.")

TypeError: compile() got an unexpected keyword argument 'optimizer'